name = "ReadStatTables"
uuid = "52522f7a-9570-4e34-8ac6-c005c74d4b84"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.1.0"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ReadStat = "d71aba96-b539-5138-91ee-935c3ee1374c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
DataAPI = "1.6"
DataFrames = "1"
DataValues = "0.4"
PooledArrays = "1.2"
PrettyTables = "1"
ReadStat = "1.1"
Tables = "1.2"
julia = "1.3"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CategoricalArrays", "DataFrames", "PooledArrays", "Test"]
