name = "ReadStatTables"
uuid = "52522f7a-9570-4e34-8ac6-c005c74d4b84"
authors = ["Junyuan Chen <norman.chen.git@gmail.com>"]
version = "0.2.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ReadStat_jll = "a4dc8951-f1cc-5499-9034-9ec1c3e64557"
SentinelArrays = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CEnum = "0.4"
CategoricalArrays = "0.10"
DataAPI = "1.13"
DataFrames = "1"
InlineStrings = "1.1"
PooledArrays = "1"
PrecompileTools = "1"
PrettyTables = "1, 2"
ReadStat_jll = "1.1.5"
SentinelArrays = "1.2"
StructArrays = "0.6"
Tables = "1.2"
julia = "1.3"

[extras]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CategoricalArrays", "DataFrames", "Test"]
